/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./api/context"


declare global {
  interface NexusGenCustomOutputProperties<TypeName extends string> {
    crud: NexusPrisma<TypeName, 'crud'>
    model: NexusPrisma<TypeName, 'model'>
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  CommentCommentsOrderByInput: { // input type
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  CommentCreateInput: { // input type
    body?: string | null; // String
    comments?: NexusGenInputs['CommentCreateNestedManyWithoutParentInput'] | null; // CommentCreateNestedManyWithoutParentInput
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    parent?: NexusGenInputs['CommentCreateNestedOneWithoutCommentsInput'] | null; // CommentCreateNestedOneWithoutCommentsInput
    post?: NexusGenInputs['PostCreateNestedOneWithoutCommentsInput'] | null; // PostCreateNestedOneWithoutCommentsInput
    username: string; // String!
  }
  CommentCreateManyParentInput: { // input type
    body?: string | null; // String
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: number | null; // Int
    postId: number; // Int!
    username: string; // String!
  }
  CommentCreateManyParentInputEnvelope: { // input type
    data?: NexusGenInputs['CommentCreateManyParentInput'][] | null; // [CommentCreateManyParentInput!]
    skipDuplicates?: boolean | null; // Boolean
  }
  CommentCreateNestedManyWithoutParentInput: { // input type
    connect?: NexusGenInputs['CommentWhereUniqueInput'][] | null; // [CommentWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['CommentCreateOrConnectWithoutParentInput'][] | null; // [CommentCreateOrConnectWithoutParentInput!]
    create?: NexusGenInputs['CommentCreateWithoutParentInput'][] | null; // [CommentCreateWithoutParentInput!]
    createMany?: NexusGenInputs['CommentCreateManyParentInputEnvelope'] | null; // CommentCreateManyParentInputEnvelope
  }
  CommentCreateNestedOneWithoutCommentsInput: { // input type
    connect?: NexusGenInputs['CommentWhereUniqueInput'] | null; // CommentWhereUniqueInput
    connectOrCreate?: NexusGenInputs['CommentCreateOrConnectWithoutCommentsInput'] | null; // CommentCreateOrConnectWithoutCommentsInput
    create?: NexusGenInputs['CommentCreateWithoutCommentsInput'] | null; // CommentCreateWithoutCommentsInput
  }
  CommentCreateOrConnectWithoutCommentsInput: { // input type
    create: NexusGenInputs['CommentCreateWithoutCommentsInput']; // CommentCreateWithoutCommentsInput!
    where: NexusGenInputs['CommentWhereUniqueInput']; // CommentWhereUniqueInput!
  }
  CommentCreateOrConnectWithoutParentInput: { // input type
    create: NexusGenInputs['CommentCreateWithoutParentInput']; // CommentCreateWithoutParentInput!
    where: NexusGenInputs['CommentWhereUniqueInput']; // CommentWhereUniqueInput!
  }
  CommentCreateWithoutCommentsInput: { // input type
    body?: string | null; // String
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    parent?: NexusGenInputs['CommentCreateNestedOneWithoutCommentsInput'] | null; // CommentCreateNestedOneWithoutCommentsInput
    post?: NexusGenInputs['PostCreateNestedOneWithoutCommentsInput'] | null; // PostCreateNestedOneWithoutCommentsInput
    username: string; // String!
  }
  CommentCreateWithoutParentInput: { // input type
    body?: string | null; // String
    comments?: NexusGenInputs['CommentCreateNestedManyWithoutParentInput'] | null; // CommentCreateNestedManyWithoutParentInput
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    post?: NexusGenInputs['PostCreateNestedOneWithoutCommentsInput'] | null; // PostCreateNestedOneWithoutCommentsInput
    username: string; // String!
  }
  CommentWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  IntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: number[] | null; // [Int!]
  }
  IntNullableFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntNullableFilter'] | null; // NestedIntNullableFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedIntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedIntNullableFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntNullableFilter'] | null; // NestedIntNullableFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedStringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  NestedStringNullableFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringNullableFilter'] | null; // NestedStringNullableFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  PostCommentsOrderByInput: { // input type
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  PostCommentsWhereInput: { // input type
    parentId?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
  }
  PostCreateNestedOneWithoutCommentsInput: { // input type
    connect?: NexusGenInputs['PostWhereUniqueInput'] | null; // PostWhereUniqueInput
    connectOrCreate?: NexusGenInputs['PostCreateOrConnectWithoutCommentsInput'] | null; // PostCreateOrConnectWithoutCommentsInput
    create?: NexusGenInputs['PostCreateWithoutCommentsInput'] | null; // PostCreateWithoutCommentsInput
  }
  PostCreateOrConnectWithoutCommentsInput: { // input type
    create: NexusGenInputs['PostCreateWithoutCommentsInput']; // PostCreateWithoutCommentsInput!
    where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
  }
  PostCreateWithoutCommentsInput: { // input type
    body?: string | null; // String
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    passwordDigest: string; // String!
    title: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    username: string; // String!
  }
  PostInputType: { // input type
    body: string; // String!
    id?: number | null; // Int
    password: string; // String!
    title: string; // String!
    username: string; // String!
  }
  PostWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  QueryCommentsOrderByInput: { // input type
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  QueryCommentsWhereInput: { // input type
    parentId?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    postId?: NexusGenInputs['IntFilter'] | null; // IntFilter
  }
  QueryPostsOrderByInput: { // input type
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  QueryPostsWhereInput: { // input type
    body?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    title?: NexusGenInputs['StringFilter'] | null; // StringFilter
  }
  StringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  StringNullableFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringNullableFilter'] | null; // NestedStringNullableFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
}

export interface NexusGenEnums {
  SortOrder: "asc" | "desc"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
}

export interface NexusGenObjects {
  Comment: { // root type
    body?: string | null; // String
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    username: string; // String!
  }
  Mutation: {};
  Post: { // root type
    body?: string | null; // String
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    title: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
    username: string; // String!
  }
  Query: {};
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  Comment: { // field return type
    body: string | null; // String
    comments: NexusGenRootTypes['Comment'][]; // [Comment!]!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    parent: NexusGenRootTypes['Comment'] | null; // Comment
    post: NexusGenRootTypes['Post'] | null; // Post
    username: string; // String!
  }
  Mutation: { // field return type
    createComment: NexusGenRootTypes['Comment']; // Comment!
    createPost: NexusGenRootTypes['Post'] | null; // Post
    deletePost: boolean | null; // Boolean
    updatePost: NexusGenRootTypes['Post'] | null; // Post
  }
  Post: { // field return type
    body: string | null; // String
    comments: NexusGenRootTypes['Comment'][]; // [Comment!]!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    title: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
    username: string; // String!
  }
  Query: { // field return type
    comments: NexusGenRootTypes['Comment'][]; // [Comment!]!
    posts: NexusGenRootTypes['Post'][]; // [Post!]!
  }
}

export interface NexusGenFieldTypeNames {
  Comment: { // field return type name
    body: 'String'
    comments: 'Comment'
    createdAt: 'DateTime'
    id: 'Int'
    parent: 'Comment'
    post: 'Post'
    username: 'String'
  }
  Mutation: { // field return type name
    createComment: 'Comment'
    createPost: 'Post'
    deletePost: 'Boolean'
    updatePost: 'Post'
  }
  Post: { // field return type name
    body: 'String'
    comments: 'Comment'
    createdAt: 'DateTime'
    id: 'Int'
    title: 'String'
    updatedAt: 'DateTime'
    username: 'String'
  }
  Query: { // field return type name
    comments: 'Comment'
    posts: 'Post'
  }
}

export interface NexusGenArgTypes {
  Comment: {
    comments: { // args
      orderBy?: NexusGenInputs['CommentCommentsOrderByInput'][] | null; // [CommentCommentsOrderByInput!]
    }
  }
  Mutation: {
    createComment: { // args
      data: NexusGenInputs['CommentCreateInput']; // CommentCreateInput!
    }
    createPost: { // args
      data?: NexusGenInputs['PostInputType'] | null; // PostInputType
    }
    deletePost: { // args
      id: number; // Int!
      password: string; // String!
    }
    updatePost: { // args
      data?: NexusGenInputs['PostInputType'] | null; // PostInputType
    }
  }
  Post: {
    comments: { // args
      orderBy?: NexusGenInputs['PostCommentsOrderByInput'][] | null; // [PostCommentsOrderByInput!]
      where?: NexusGenInputs['PostCommentsWhereInput'] | null; // PostCommentsWhereInput
    }
  }
  Query: {
    comments: { // args
      after?: NexusGenInputs['CommentWhereUniqueInput'] | null; // CommentWhereUniqueInput
      before?: NexusGenInputs['CommentWhereUniqueInput'] | null; // CommentWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenInputs['QueryCommentsOrderByInput'][] | null; // [QueryCommentsOrderByInput!]
      where?: NexusGenInputs['QueryCommentsWhereInput'] | null; // QueryCommentsWhereInput
    }
    posts: { // args
      after?: NexusGenInputs['PostWhereUniqueInput'] | null; // PostWhereUniqueInput
      before?: NexusGenInputs['PostWhereUniqueInput'] | null; // PostWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenInputs['QueryPostsOrderByInput'][] | null; // [QueryPostsOrderByInput!]
      where?: NexusGenInputs['QueryPostsWhereInput'] | null; // QueryPostsWhereInput
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}